### ISSUE TITLE
Scrollbar isn't visible after selecting album

### ISSUE THREAD

**Issue by sridharjajoo** [fossasia/phimpme-android#1232]
**Actual Behaviour**
The scrollbar isn't visible after selecting any of the album.

**Expected Behaviour**
The scrollbar should be visible.

**Steps to reproduce it**
Select any of the album.

**Would you like to work on the issue?**
Yes

**Comment by sachincool** [comment]
@sridharjajoo Please post the screenshot regarding the Actual and Expected behaviour if there are any  UI changes. Also   read the [Best practices @fossasia](https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/) for a better idea on your  future contibutions . thank you so much for understanding :smile:
