### ISSUE TITLE
Replace toggle button action with swipe gestures

### ISSUE THREAD

**Issue by aditya98ak** [fossasia/phimpme-android#1434]
**Actual Behaviour**

Currently, we have a toggle button, clicking on which changes colours/filters.
![temp](https://user-images.githubusercontent.com/21143936/32141564-bf1f6602-bca9-11e7-9778-b55e37e9c2e6.jpeg)
Currently Clicking on the toggle button, changes filters.

**Expected Behaviour**

What if that button is replaced by swipe gestures?

**Would you like to work on the issue?**

Yes.
What do you say @mohitmanuja @anantprsd5 @sridharjajoo @nikit19 @codedsun

**Comment by codedsun** [comment]
I have opened an similar issue and I am working on it.
I have my keyboard broken and not able to work properly.

**Comment by codedsun** [comment]
https://github.com/fossasia/phimpme-android/issues/1312

**Comment by aditya98ak** [comment]
@codedsun I think swiping gestures if implemented for changing colours will be more awesome then changing b/w camera, gallery, accounts.
@nikit19 @sridharjajoo What do you say?

**Comment by nikit19** [comment]
@aditya98ak I didn't get what you are trying to implement. Can you elaborate a little more and how is it different from #1312

**Comment by aditya98ak** [comment]
@nikit19 We have a toggle button for changing colours, so I am saying is that instead of toggle button we can use left and right swipe gestures to change colour.
and #1312 @codedsun is trying to implement that on swiping from right to left we can navigate b/w camera activity, LFMainActivity and accounts activity.
@codedsun Am I correct?

Hope I am clear this time. @nikit19

**Comment by aditya98ak** [comment]
@nikit19 @sridharjajoo @codedsun What should be done, only one among the two i.e #1434 and #1312, can be implemented.
Which one to be closed?

**Comment by codedsun** [comment]
@aditya98ak I am implementing swipe gesture on the LFMainActivity not the camera activity, you shall go with that but somewhat it will be a confusion to the users because as in most of the apps, they also have swipe feature with preview of what filters are applied example retrica but if we are only having swipe gestures, it might happen that people will not able to know about this feature.

**Comment by aditya98ak** [comment]
@codedsun We can notify them when the user first opens cameraActivity?

**Comment by mayank8318** [comment]
@aditya98ak How about we use two finger swipe for colours and effects and simple swipe for navigation?

**Comment by aditya98ak** [comment]
@mayank8318 In what way the user will swipe with two fingers?

**Comment by mayank8318** [comment]
@aditya98ak Two fingers in camera mode for changing filters and single finger swipe for navigation which will be consistent throughout the app. How does this sound? Is it too much for the user?

**Comment by mayank8318** [comment]
@aditya98ak If we look at a similar Industrial app like Snapchat, they have swipe for navigation and for filters you need swipe the lower panel where the capture button is located.
But in Snapchat all the filters are shown below so the user knows that swiping the lower panel means changing filters as the current filter slides into the capture button

**Comment by mohitmanuja** [comment]
@mayank8318 @aditya98ak @codedsun No need to add swipe gestures for camera ->gallery-> accounts.
Yes we can think to add filters with swipe gestures but before this please try to add some fancy filters because currently there are inbuilt filters which most users will not use. So first try to create some filters and after that proceed with swipe feature. 
I hope it is clear to all.

**Comment by abishekvashok** [comment]
Using swipe gestures on the camera screen can be confusing as with the bottom navigation bar is present. Thereby closing this one.
