### ISSUE TITLE
Bug on Image Adding to Favourites

### ISSUE THREAD

**Issue by codedsun** [fossasia/phimpme-android#1483]
**Actual Behaviour**

Their is a bug on adding image to the favourites, no changes are made no special icon or a folder is made for favorites.

**Expected Behaviour**

A separate favorite folder should be made and the images which are favorited should have a special icon of heart emoticon or something like that.

And there should be a feature to remove the app from the favorite too!

**Would you like to work on the issue?**

Yes! @madhavrathi @mayank8318 @aditya98ak @mohitmanuja @anantprsd5

**Comment by sauravvishal8797** [comment]
@codedsun I had created an issue for this. #1289. I have divided the issue to 2 parts one being adding to the favorites table and another to display it a new favourites activity. I have mentioned this in the first PR #1320. Due to my college exams I'm not able to work on it currently,  but will resume work by the end of this week.

**Comment by codedsun** [comment]
@sauravvishal8797 OK ! Closing this issue.
