### ISSUE TITLE
	Gradle sync failed: A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by vishant16** [fossasia/phimpme-android#1484]

**Comment by nb2998** [comment]
@vishant16 If you are doing it for the first time, follow each and every step given under the [development setup](https://github.com/fossasia/phimpme-android#development-setup) carefully. 
Doing so should solve the issue.

**Comment by codedsun** [comment]
@vishant16 Kindly provide the logs for the issue and ask in the channel if you get stuck anywhere.

**Comment by vishant16** [comment]
Gradle 'phimpme-android' project refresh failed
Error:A problem occurred configuring project ':app'.

pls solve it

**Comment by AbsolutelySaurabh** [comment]
@vishant16 
Solved:
Follow the steps as mentioned under the "development setup".
If I am not wrong, you might haven't followed the OpenCV section in the "development guide", that's why u're getting this error. 
Follow those steps and creating/copying the mentioned folders in the project from the downloaded OpenCV-android-sdk/sdk/native/ folder.

**Comment by KiranRajR** [comment]
It happens because Build Tools revision 24.4.1 doesn't exist.

The latest version is 23.0.2.
These tools is included in the SDK package and installed in the <sdk>/build-tools/ directory.

Don't confuse the Android SDK Tools with SDK Build Tools.

Change in your build.gradle

android {
   buildToolsVersion "23.0.2"
   // ...

}

**Comment by airman00** [comment]
Happened to us because ndk-bundle was "missing platforms"

Solution was simply to add an empty platforms/ folder to the sdk/ndk-bundle directory.
