### ISSUE TITLE
Use action bar instead of toolbar tag in xml

### ISSUE THREAD

**Issue by rohanagarwal94** [fossasia/phimpme-android#160]
**Actual Behaviour**

Toolbar widget is being used in every layout xml of fragments.

**Expected Behaviour**

Use action bar in the app theme. This will help in getting overflow menu in the action bar and share icon need not be included in every xml.

**Screenshots of the issue**

![screenshot from 2017-03-17 21-43-43](https://cloud.githubusercontent.com/assets/13241256/24052376/4654d9d2-0b5b-11e7-9201-17e83b2ed632.png)

**Would you like to work on the issue?**

Yes, I would like to work on it.

**Comment by dynamitechetan** [comment]
toolbar was made intentionally to have more space on map and camera fragment.

**Comment by rohanagarwal94** [comment]
@dynamitechetan a better way to do that is declaring a separate theme for camera and map activity with no action bar. I will be doing that in submission of PR of this issue itself.

**Comment by heysadboy** [comment]
@rohanagarwal94 I added toolbar instead of action bar because it allows more customization than action bar. Look it up http://stackoverflow.com/questions/27665018/what-is-the-difference-between-action-bar-and-newly-introduced-toolbar . Our UI is evolving, we'll have more options by using that. @dynamitechetan I correct.

**Comment by rohanagarwal94** [comment]
Got it. Hence closing it.
