### ISSUE TITLE
Modifications required in the search functionality.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1659]
**Actual Behaviour**

Issues in the search functionality.

- [ ] Soft-keyboard should automatically pop up when the focus is on search view. 

- [ ] Appropriate message should be displayed if search result is null. 

**Expected Behaviour**

Soft-keyboard should automatically pop up when the search view gets focus.
Proper message should be displayed if the search results are null.

**Steps to reproduce it**

Perform the search operation.

**Would you like to work on the issue?**

Yes.

**Comment by codedsun** [comment]
@sauravvishal8797 With respect to first, we have keyboard popping up on focus to search bar. Confirmed @nikit19 .

And do we require a sort on the search? your views @mayank8318 @nikit19 Because there are many features already being present in the Phimpme and adding more features will only make the app more lagging.

**Comment by mayank8318** [comment]
At this stage I don't think we need sorting or speech for searching. As these are just album names, in my opinion speech is not required here and sorting too since the no of results are bound to be few.

**Comment by nikit19** [comment]
I agree with @mayank8318 and I think that the third point
 "The bottom bar should be hidden in the search mode" is also not required as the bottom bar will always be hidden under the soft keyboard
