### ISSUE TITLE
Add to favorites option visible for hidden photos. 

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1710]
**Actual Behaviour**

Add to favorites option is visible for hidden photos. 

**Expected Behaviour**

Add to favorites option should not be visible for hidden photos, 

**Steps to reproduce it**

Select photo/photos in any of the hidden folders and click on the overflow menu. 

**Would you like to work on the issue?**

Yes.

**Comment by raj10071997** [comment]
@sauravvishal8797 It is good that favourite option is visible for hidden photos as if the user wants to add some photos from the hidden folders, he/she can directly photos to favourites rather than first unhiding those photos and then adding them to favourites.

**Comment by sauravvishal8797** [comment]
@raj10071997 I don't think that the hidden and non-hidden photos should be mixed, which will be the case if adding to favourites is allowed from the hidden folders. And hiding is performed to keep the photos private whereas the favourites collection at this moment is sort of a public folder so I don't think hidden photos should be allowed to be added to favourites or any other non-hidden folder.

**Comment by raj10071997** [comment]
@sauravvishal8797  But it totally depends on the user whether he/she wants to add the hidden photos to favourites. If he/she wants to add the photos to favourites, then having an option for that in the overflow menu is an easy way to do that rather than first unhiding those photos and then adding them to favourites. You are right about the private property of the hidden folder but it totally depends on the user whether to make his/her photos public. I am only talking about the ease of the task.
