### ISSUE TITLE
why there is a clear selected option in HiddenFolders.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1773]
**Actual Behaviour**
There is clear selected option only in the overflow menu for HiddenFolders and not anywhere else. 

**Expected Behaviour**

There is no need of this option as the cross in the toolbar unselect the selected objects.

**Screenshots of the issue**

![27605597_2014565905485171_953029622_o](https://user-images.githubusercontent.com/24502136/35565360-4b9db5d4-05e3-11e8-9b83-0a91336f7968.jpg)

**Would you like to work on the issue?**
Yes

**Comment by sauravvishal8797** [comment]
@raj10071997 The clear selected option is to clear the selected items when all the albums are selected, and when you select a few albums the select all option is displayed. Since in your screenshot only one folder is there to select, clear selected option is visible. Please check this feature by performing the long press operation for the local folders.

**Comment by raj10071997** [comment]
@sauravvishal8797  but why clear selected option is present when there is clearly a cross sign present in the toolbar. This create a redundancy. I agree that if you select few albums there should be a select all option but why clear selected when there is a cross sign present in the toolbar.

**Comment by sauravvishal8797** [comment]
@raj10071997 In that case what you can do is when all the albums are selected, you can change the visibility of the select all option to false, I guess.

**Comment by raj10071997** [comment]
@sauravvishal8797  Yes, I was thinking the same thing.
