### ISSUE TITLE
Favourites photos issue.

### ISSUE THREAD

**Issue by sauravvishal8797** [fossasia/phimpme-android#1778]
**Actual Behaviour**

When there are no photos added to the favourites collection, sort option is still visible.

**Expected Behaviour**

Sort option should only be visible if there are photos added to the favourites collection.

**Steps to reproduce it**

Remove all the photos from Favourites if any.

**Would you like to work on the issue?**

Yes.

**Comment by raj10071997** [comment]
@sauravvishal8797 There is no need of removing the sort option as this option is visible everywhere even after removing all the albums in LFMainActivity and even in hidden folders. Suppose if you add some photos to favourites there should be some order in which those photos should be added. So in my view there should be a sort option even when there are no photos, so that when some photos are added they should be added in some order.

**Comment by ashley8jain** [comment]
I agree with @raj10071997 . @sauravvishal8797 close this issue.

**Comment by abishekvashok** [comment]
I am gonna close this
