### ISSUE TITLE
Infomation with their tags is not assigned properly in details of an image.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1850]
**Actual Behaviour**

See the below screenshot for the issue. The title of the tag title is not aligned properly. Similarly, Path is also not aligned properly with it's tag.

**Expected Behaviour**

All the information should be aligned properly with their tags.

**Screenshots of the issue**

![details](https://user-images.githubusercontent.com/24502136/36139912-5ff8c8b0-10c5-11e8-8785-6a50835c4bb1.png)

**Would you like to work on the issue?**

Yes.

**Comment by sauravvishal8797** [comment]
@raj10071997 I guess it's aligned alright for the path tag, since the last text takes up more space the above two are aligned in that manner. You can check this for other images. And for the title part if the title extends to more than a single line the alignment is fine, only for the single line cases it's needed to be changed.

**Comment by raj10071997** [comment]
@sauravvishal8797 I was talking about the starting of the path text, that it's bottom must be aligned with the bottom of it's tag. The bottom must be aligned with it's tag properly, otherwise consider the case when the path is too long then path text will start much above the Path tag which doesn't look nice which is in this case.
