### ISSUE TITLE
The toolbar is overlapping the image in ShareActivity.

### ISSUE THREAD

**Issue by raj10071997** [fossasia/phimpme-android#1926]
**Actual Behaviour**

When you click on the share icon in the bottom bar in SingleMediaActivity and open the share activity the tool bar is overlapping the image.

**Expected Behaviour**

The tool bar shouldn't overlap the image.

**Screenshots of the issue**

![share](https://user-images.githubusercontent.com/24502136/36943534-2462f4f6-1fb1-11e8-9db1-da906e12fa17.png)

**Would you like to work on the issue?**

Yes.

**Comment by DhruvamSharma** [comment]
Same as https://github.com/fossasia/phimpme-android/issues/1873

**Comment by raj10071997** [comment]
@DhruvamSharma  The issue #1873 specifies that it is related to SingleMediaActivity which is in this case, is not similar to this issue.

**Comment by DhruvamSharma** [comment]
I have made an issue for this as well. I'll mention the Issue no.

On Mar 5, 2018 11:46 AM, "Dhanraj Sahu" <notifications@github.com> wrote:

@DhruvamSharma <https://github.com/dhruvamsharma> The issue #1873
<https://github.com/fossasia/phimpme-android/issues/1873> specifies that it
is related to SingleMediaActivity which is in this case, is not similar to
this issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/phimpme-android/issues/1926#issuecomment-370320428>,
or mute the thread
