### ISSUE TITLE
Filter in Accounts [Featue] 

### ISSUE THREAD

**Issue by Ananthusubramanian** [fossasia/phimpme-android#1946]
Search bar in accounts helps the user to search the accounts easily .
![screenshot_2018-03-10-17-13-08-625_org fossasia phimpme](https://user-images.githubusercontent.com/22250995/37241929-24428a56-2487-11e8-8ccc-e08f65ffb705.png)

**Comment by Ananthusubramanian** [comment]
Can I work on this issue?

**Comment by sauravvishal8797** [comment]
@Ananthusubramanian Since only few options are there in the accounts section I don't think it's required here. The user might prefer to scroll rather than entering query to search again as limited options are available.

**Comment by Ananthusubramanian** [comment]
@sauravvishal8797  This search filters  account according to name of the accounts.And the accounts list is being expanding ,so search would be necessarily and after the sign up the text of items change ,it would be difficult to look .So users can filter the accounts.

**Comment by abishekvashok** [comment]
If you are going to implement so I recommend to follow material design guidelines more closely for the search box.

**Comment by Ananthusubramanian** [comment]
@abishekvashok Thanks for suggestion and approval .Can I get a example screenshot of material design searchbox  for doing so.

**Comment by abishekvashok** [comment]
Similar to the card view one.

**Comment by codedsun** [comment]
What we can implement here is that the signed in account should be shown at the top of list and the other accounts below them, it will remove the task of searching the account and looks more attractive. And as per your goal, we dont' have many items in the account list so this is an extra extra feature which will make our app not suitable to users I think. Because we dont' like. an app that's either too featured that it becomes complex to the end user and less featured that no task can be done through the app. These are my views.

**Comment by Ananthusubramanian** [comment]
@codedsun I will do that too.
