### ISSUE TITLE
pass value from main activity to second activity

### ISSUE THREAD

**Issue by Jwarraich** [fossasia/phimpme-android#2022]
I'm making an app in which points are calculated for the basketball team. We can add points like one, two and three according to the goal and their total is displayed on the same page. But now i want to pass the value of total on new activity and display it there as team A's total score is 34 or whatever it is. Please help me to do that. I've created a method to perform calculations and that calculated value is displayed on the "score" textView . Now i want to show this "score" textView's value on new activity using intent. Please help me.

**Comment by sauravvishal8797** [comment]
Yes, you can pass value from one activity to another activity using intent, and in the oncreate method of the second activity, you can retrieve the value by the getIntent() method. Please, first search on the internet for all the doubts you have while coding because you'd get all the solutions you require on the internet. And please do not create issues for asking questions, you can do that in the public channels of organizations. And therefore I'm closing this issue.
