### ISSUE TITLE
Adding layout resizing functionality in editor activity(landscape mode)

### ISSUE THREAD

**Issue by codepoet2017390** [fossasia/phimpme-android#2166]
**Actual Behaviour**

Presently when an image is being edited in the landscape mode the filters are not displayed correctly and the it looks like the attached screenshot.The left margin of the image view is hard-coded to be 60dp. 

**Expected Behaviour**
The user should be able to slide the left layout bound separating the imageview and the filter templates as per his/her convenience.

**Steps to reproduce it**

1. Click a picture and go to Editing activity.
2. Now rotate the screen to landscape mode.
3. The attached screenshot is seen.

**Screenshots of the issue**
![whatsapp image 2018-09-15 at 01 49 33](https://user-images.githubusercontent.com/37406965/45575115-01374180-b890-11e8-9f88-5c821b14ebf5.jpeg)

**Would you like to work on the issue?**
    Yes

**Comment by abishekvashok** [comment]
Hey, great job finding the bug.
But, I guess instead of letting the user slide the images it would be much more professional, if the image resizes itself based on the size of the filter view container. We could also resize the filter view container. Can you consider these two solutions instead of adding the proposed solution, please?
