### ISSUE TITLE
Cloudrail license key is missing 

### ISSUE THREAD

**Issue by kk63852** [fossasia/phimpme-android#2420]
**Actual Behaviour**

cloudrail license key is left blank.

**Expected Behaviour**

the license key should be added or dropbox feature should be removed.

**Steps to reproduce it**

go to accounts settings and navigate to dropbox. tapping on it displays a toast saying cloudrail license key not found.

**Would you like to work on the issue?**

yes.

**Comment by kk63852** [comment]
how do i get the license key ? @abishekvashok @sauravvishal8797

**Comment by sauravvishal8797** [comment]
@kk63852 You can go to cloudrail.com and sign up for a developer account to get the license key. After you get the license key, you can use it for your local development purposes whenever you're working on any of the cloudrail implementations in the app. However, since this is the development phase of the app there is no need to add the license key here. This is only to be added at the time of production.
