### ISSUE TITLE
No option to show details of a photo

### ISSUE THREAD

**Issue by naman653** [fossasia/phimpme-android#2491]
**Actual Behaviour**

There is no option in the menu list on activity showing all the photos of an album.

**Expected Behaviour**

There should be an option for showing details if one image is selected in All Photos activity.

**Would you like to work on the issue?**

Yes

**Comment by yashk2000** [comment]
@naman653 I don't think there is any need for this. The option to see image details can be pressed without even opening the menu. Hence placing a similar option in the menu would have no use.

**Comment by yashk2000** [comment]
@naman653 this way we could have added all options provided such as edit, resize, add to favourites etc to the menu. Those haven't been added as they are available to the user without opening the menu. That's why I think this feature would be redundant. There's no point in having a less accessible button when a more accessible one already exists.
