### ISSUE TITLE
Select/deselect all feature is absent in security option

### ISSUE THREAD

**Issue by alphamuth** [fossasia/phimpme-android#2511]
**Actual Behaviour**

There is absence of select all files or deselect all  feature in security files option, which may be very tiresome for users if there are huge number of folders or files.
**Expected Behaviour**

An option for select/deselect all should be present.

**Screenshots of the issue**

![screenshot_20190210-003803](https://user-images.githubusercontent.com/37583853/52525314-90287880-2ccd-11e9-8f57-97c9f051d36d.png)

**Would you like to work on the issue?**
yes

**Comment by yashk2000** [comment]
@imrrahul deselect all is basically turning off security on local folders. Select all option already has an issue, #2447 . Please ask @kk63852 before working on that issue.

**Comment by imrrahul** [comment]
@yashk2000 yes I agree it will be used to turn off security on all folders but the problem is if I again want to deselect my previously (assume a,b,c) selected folder and now I want to select (x,y,z) then I have to deselect one by one (a,b,c) and this may be very irritating for persons like me so why not provide features such as deselect all and start selecting from begining.

**Comment by imrrahul** [comment]
#2447 @kk63852 are you working on this issue ?

**Comment by imrrahul** [comment]
#2447 @kk63852 are you working on this issue?

**Comment by yashk2000** [comment]
> @yashk2000 yes I agree it will be used to turn off security on all folders but the problem is if I again want to deselect my previously (assume a,b,c) selected folder and now I want to select (x,y,z) then I have to deselect one by one (a,b,c) and this may be very irritating for persons like me so why not provide features such as deselect all and start selecting from begining.

For this I have created #2368 and am working on it.

**Comment by imrrahul** [comment]
@yashk2000 #2368 Yes this is the issue I was talking  about, so go ahead and work on it .....thanks

**Comment by kk63852** [comment]
> #2447 @kk63852 are you working on this issue?

Go ahead.

**Comment by theabhishekavi** [comment]
@yashk2000 @imrrahul @kk63852  I found this bug too. Basically, i was thinking to add an onclicklistener on the textview 'Local Folder' which will open the the same dialog box of the secured folder and we don't need to toggle on and off again and again. And one more thing, when we go back and open the securedfolder list we get an empty dialog box. All the previous local folder list is lost. As a good practice we should always show the previously selected folders. If anyone is not working on this issue,shall i take this issue?

**Comment by yashk2000** [comment]
@theabhishekavi I will be working on this issue, #2368. I have almost done it. I have made a separate text view of "Choose Folders" which is visible only when security on local folders is on. This way the toggle switch stays. I've set an OnClickListener on the "Choose Folders". I have to work on the part where the previously selected folders are already checked.

**Comment by theabhishekavi** [comment]
@yashk2000 Actually i have also done the same. I was about to raise an issue and send a pull request then i saw this issue. If you want any help to show the previously locked file in dialog box then feel free to say me because i have already done it. And rest is my fault because i started to work on this without raising an issue and seeing it.

**Comment by yashk2000** [comment]
Closing this issue as it was already implemented, but we no longer have security settings.
