### ISSUE TITLE
Enable swipe to refresh when activity is empty.

### ISSUE THREAD

**Issue by yashk2000** [fossasia/phimpme-android#2722]
**Describe the bug**
Swipe to refresh is disabled in empty activities view. It should be enabled.
**Would you like to work on the issue?**

- [X] Yes
- [ ] No
- Other:

**Comment by abishekvashok** [comment]
Why should we remove it?

**Comment by yashk2000** [comment]
There is no for swipe to refresh if there are no favorites in favoritesList. Also, this has already been done for some other activities, but favorites was left out.

**Comment by sparrow007** [comment]
i am agree with @abishekvashok  because currently swipe to refresh represents the good user experience means we are developer we know if there is no item it simply show the message but from perspective of the user swipe to refresh shows list is empty but it may be updated (good interactions with app).

**Comment by yashk2000** [comment]
Then shall I change the issue to enable swipe to refresh for those activities for which it has been disabled?

**Comment by sparrow007** [comment]
yes and also call the method for refreshing (update) the list.

**Comment by yashk2000** [comment]
the list automatically gets updated when favorites is opened or swiping to refresh is done.
@sauravvishal8797 what are your views on this?

**Comment by yashk2000** [comment]
@abishekvashok should I enable swipe to refresh for those activities for which it has been disabled?
