### ISSUE TITLE
Delete Password Feature and give Access to Everything Without Password

### ISSUE THREAD

**Issue by mariobehling** [fossasia/phimpme-android#2736]
People already use a password etc. to access their phone. We only have a small team and should not take care of features that are already taken care of by the system.

Please take out the password feature entirely.

Other reasons:
* it is not the task of the app to control access within the device (anyone who has access to the phone can easily circumvent that anyways)
* we don't have an easy way to reset passwords through email reset (like online services)
-> We should not take our time to maintain password features and it is not a high requirement stopping users from flocking to the app.

**Comment by yashk2000** [comment]
@mariobehling since our app also serves as a gallery app, that's why there is the security feature. The users should be provided an option to secure their photos even if they can be circumvented by anyone. Also the security feature currently has almost everything except fingerprint access which we can keep as low priority and implement later. So there no current need of maintaining the feature.
We should not keep maintaining the security features a primary priority. It can be of low priority after we are done with other major features.
