### ISSUE TITLE
Wordpress upload not working with new version

### ISSUE THREAD

**Issue by pa1pal** [fossasia/phimpme-android#53]
The current implementation of wordpress works only for older versions. Because of plugins gets deprecated. New version are not supported.

**Comment by rohanagarwal94** [comment]
@pa1pal I am developing a native solution for this where the user will be logging in and then will select his site( if he has more than 1 sites) where the media will be uploaded. Anything else to look out for???

**Comment by Abhi2424shek** [comment]
He will have the option to choose it? @rohanagarwal?

**Comment by rohanagarwal94** [comment]
Oh yes, probably in recyclerview.

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 6, 2017 at 3:01 PM, Abishek V Ashok<notifications@github.com> wrote:   
He will have the option to choose it? @rohanagarwal?

**Comment by pa1pal** [comment]
@rohanagarwal94 every account will be shown as a separate account. You can add multiple wordpress accounts. Other than media, there was a text field as well, where you can write the message.

**Comment by rohanagarwal94** [comment]
@pa1pal what I am trying to convey is there is a difference between uploading a media and publishing a media. I will be adding a login page if the user has not already logged in. On logging in, the user will be shown multiple sites which he has created with wordpress. On selecting a site, a dialog will pop-up to confirm upload to the site. Point to note here is that this will not publish the images selected in the upload.java as a blog post but just upload to the cloud storage of the respective website on the same account. Further on selecting the site, a gridview will show the uploaded media to the particular site. On selecting a particular image, the user will be able to edit the caption and the description. Correct me if I am wrong or the workflow requires change. :)

**Comment by pa1pal** [comment]
Your workflow is fine, but can't accounts be on multiple sites basis? and we select publishing the media as out priority.
Because what we want in phimpme is many upload right from one click. So let say when app will have 10 accounts, then user just simply mark the account which he/ she wants to upload and press one button. Rest the app will upload one by one and not block the UI thread.

**Comment by rohanagarwal94** [comment]
The only account I am talking right now is of Wordpress. Now as far as checklist goes, it will encounter some problems in the case of a Wordpress account. Firstly, the user should be logged into the particular account. If suppose the Wordpress and Drupel are not logged in, how will the UI flow be in order to make him login into both?
Secondly as explained earlier, a user can create multiple websites within a single account on Wordpress. Therefore the media upload cannot be automatic if the user has one than one website in his account. Thirdly, the media publishing as a blog post will have text description, title and other fields. How will we be able to achieve that if we try to upload more than 1 images simultaneously to the Wordpress with 1 click?

**Comment by rohanagarwal94** [comment]
@pa1pal final take on this? I am solving this on priority than other issues.

**Comment by pa1pal** [comment]
@rohanagarwal94 go ahead with your idea and firstly please see the current wordpress mobile app may be we get some idea from there. Because earlier implementation was exactly like the wordpress mobile app.

**Comment by rohanagarwal94** [comment]
@pa1pal I will take that into account :+1:
