### ISSUE TITLE
Sorting option is not working for Albums

### ISSUE THREAD

**Issue by anantprsd5** [fossasia/phimpme-android#830]
**Actual Behaviour**

Sorting option is not working for the albums mode.

**Expected Behaviour**

Sorting option should work.

**Steps to reproduce it**

1. Open app.
2. Try to sort albums. 

**Would you like to work on the issue?**

Yes

**Comment by vinaysajjanapu** [comment]
@anantprsd5 It is working for me. The first item in the list is always camera album and the other albums are getting sort as per the selected mode. Please check again.
Sort by Size is not functioning correctly, it is taking number of pictures inside the album into consideration instead of size of the album.

**Comment by vinaysajjanapu** [comment]
Just refresh the page by swiping down after changing the sort mode.

**Comment by anantprsd5** [comment]
Yes. That's the issue. It should automatically refresh on clicking the sort
button.

**Comment by anantprsd5** [comment]
I thinking sorting by no. Of photos in the album is correct when using the size sort.
