### ISSUE TITLE
Add Facebook Messenger in Sharing Activity

### ISSUE THREAD

**Issue by Subhankar29** [fossasia/phimpme-android#929]
**Actual Behaviour**

There is no Facebook Messenger in Sharing Activity
**Expected Behaviour**

To add Facebook Messenger in Sharing Activity

**Would you like to work on the issue?**
Anyone wants, can assign it to your self.

**Comment by mohitmanuja** [comment]
@pa1pal @anantprsd5 @Subhankar29 @vinaysajjanapu need suggestion do we require to add this or add other account option (like messenger, telegram, etc) which basically requires apps to be installed in user device because this is what share intent does (Our other option).

So should we add in our share activity. Right now we added instagram and googleplus only.
I don't prefer to add options (like social media which require app to be installed (Share intent is enough) . What are your suggestions ?

**Comment by Subhankar29** [comment]
@mohitmanuja I think yes, to maintain the uniformity of the application we have Whatsapp, telegram, Instagram in the application not many users will connect the accounts using Accounts Activity, so they will require a quick option to share the image with friends and foe. So using share Intent is a way, but we it isn't direct though. We can take the example of the apps PicArt they did in the same way.

**Comment by Subhankar29** [comment]
@mohitmanuja Since, we already integrated Facebook SDK in our application we can use that to share the image, as stated in the docs:https://developers.facebook.com/docs/messenger/android. It is a quick and easy way to share. Benefits: User won't have to leave the application. Unlike the share Intent. That is the whole motive of our Phimpme Application.

**Comment by anantprsd5** [comment]
@Subhankar29 @mohitmanuja I think that all the share actions which require the application to be installed should be in the other share option except for most used apps like Telegram, Whatsapp. If integrating messenger share using the SDK is achievable, then it is fine to add this to share options.

**Comment by Subhankar29** [comment]
@anantprsd5 Yes, it is achievable.

**Comment by mohitmanuja** [comment]
Okay, then go ahead.
