### ISSUE TITLE
Disable pushes to slack for forks

### ISSUE THREAD

**Issue by Abhi2424shek** [fossasia/phimpme-android#95]
**Actual Behaviour**

When a commit is made on a fork, slack gets notification.

**Expected Behaviour**

Notification should not be made.

**Would you like to work on the issue?**

Yes.

**Comment by harsu-ag** [comment]
I searched for it, and it seems they are in development mode for this - [Issue](https://github.com/travis-ci/travis-ci/issues/1094)

I also found another issue very similar to ours - https://github.com/travis-ci/travis-ci/issues/4722

They have written right now the best way is to disable notifications until this issue is done.

**Comment by Abhi2424shek** [comment]
Encrypt the key

**Comment by Abhi2424shek** [comment]
Investigating...

**Comment by Abhi2424shek** [comment]
An issue is still open for this in Travis, we will reopen this issue when it is closed via a commit or PR.
